version: '3.0'

services:
  app:
    extends:
      file: docker-compose.dev.yml
      service: app
    user: "${UID}:${GID}"
    command: /bin/sh -c "npm_config_cache=/usr/src/app/.npm-cache npx nx run-tests backend"

  mongodb:
    extends:
      file: docker-compose.dev.yml
      service: db
    ports:
     - "27017:27017"

  redis:
    extends:
      file: docker-compose.dev.yml
      service: redis
    ports:
     - "6379:6379"

volumes:
  mongo_data_dev:
  redis_data_dev:

networks:
  activepieces_dev:
